apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 9090
      type: NodePort